---
title: "Toronto COVID-19 Cases Study"
author: "Xiangyu Wang"
date: 2020-09-24
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
bibliography: 'references.bib'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("opendatatoronto")
install.packages("tidyverse")
library(opendatatoronto)
library(tidyverse)
library(dplyr)
```

```{r}
toronto_covid_packages <- search_packages("COVID")
toronto_covid_resources <- toronto_covid_packages %>% list_package_resources()
toronto_covid_statistics <- toronto_covid_resources %>% get_resource()

```
#Part.i Abstract
test 
Used @citetidyverse

#Part.ii Introduction 

#Part.iii Data Introduction

```{r}
glimpse(toronto_covid_statistics)
```

The scenario and study objective.
Types of Variables

#Part.iv Including Plots

```{r}
ggplot(data = toronto_covid_statistics) +  aes (x = toronto_covid_statistics$`Age Group`) + geom_bar(color = "black",fill = "skyblue2") + labs(x = 'Age Group', y = 'Case Count', title = 'Totonto COVID-19 Case in All Age Groups')
```

```{r}
ggplot(data = toronto_covid_statistics) +  aes (x = toronto_covid_statistics$`Client Gender`) + geom_bar(color = "black",fill = "skyblue2")  + labs(x = 'Case Gender', y = 'Case Count', title = 'COVID-19 Cases with Different Gender') 
```



# Reference




